version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 15
  groups:
    all-updates:
      applies-to: version-updates
    all-security:
      applies-to: security-updates
